// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLw6pSbFhAVwPwqTC4Fboa8LlKNQkszf0',
    appId: '1:443937759282:web:bda68acccf50acc7ecdc2b',
    messagingSenderId: '443937759282',
    projectId: 'dbperiodico',
    authDomain: 'dbperiodico.firebaseapp.com',
    storageBucket: 'dbperiodico.firebasestorage.app',
    measurementId: 'G-42X1MDYYY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-PNMdV9w0zcWtKm_332R9zNm7Lv2sTvw',
    appId: '1:443937759282:android:e90b034aa7fb13dcecdc2b',
    messagingSenderId: '443937759282',
    projectId: 'dbperiodico',
    storageBucket: 'dbperiodico.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3h0_EczKoDOlu-f9lYiJxmejJ_PglWDg',
    appId: '1:443937759282:ios:b8565a07e05b2007ecdc2b',
    messagingSenderId: '443937759282',
    projectId: 'dbperiodico',
    storageBucket: 'dbperiodico.firebasestorage.app',
    iosBundleId: 'com.example.periodico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3h0_EczKoDOlu-f9lYiJxmejJ_PglWDg',
    appId: '1:443937759282:ios:b8565a07e05b2007ecdc2b',
    messagingSenderId: '443937759282',
    projectId: 'dbperiodico',
    storageBucket: 'dbperiodico.firebasestorage.app',
    iosBundleId: 'com.example.periodico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLw6pSbFhAVwPwqTC4Fboa8LlKNQkszf0',
    appId: '1:443937759282:web:d573ce8676b73321ecdc2b',
    messagingSenderId: '443937759282',
    projectId: 'dbperiodico',
    authDomain: 'dbperiodico.firebaseapp.com',
    storageBucket: 'dbperiodico.firebasestorage.app',
    measurementId: 'G-BWC1FET6Y4',
  );
}
